### ISSUE TITLE
Used with MAgent?

### ISSUE THREAD

**Issue by sunfanyunn** [PKU-AI-Edge/DGN#1]
In the paper, it is mentioned that you adopt a large-scale gridworld platform
MAgent(https://github.com/geek-ai/MAgent). 
But is it used in this code?

**Comment by z0ngqing** [comment]
No, this code is only for the third experiment (i.e., routing) in the paper

**Comment by sunfanyunn** [comment]
Is the code of the other sections released?

**Comment by z0ngqing** [comment]
Not yet.
