### ISSUE TITLE
router

### ISSUE THREAD

**Issue by CaralHsi** [PKU-AI-Edge/DGN#2]

**Comment by CaralHsi** [comment]
I cannot get the same result when running your code. It seems not convergent and the result I get is this:

1.492 | 28.10526 | 19 | 0
0.95 | 89.92308 | 13 | 0
0.866 | 111.5833 | 12 | 0
0.94 | 122.5385 | 13 | 0
0.87 | 169.7273 | 11 | 0
0.694 | 165.6667 | 12 | 0
0.842 | 168.0833 | 12 | 0
0.914 | 82.15385 | 13 | 0
1.002 | 162.2 | 15 | 0
0.478 | 130.75 | 8 | 0
0.902 | 145.8462 | 13 | 0
1.074 | 164.5333 | 15 | 0
0.744 | 183.8333 | 12 | 0
0.412 | 254.4444 | 9 | 0
0.856 | 287 | 12 | 0
1.034 | 51.08333 | 12 | 0
0.938 | 157.8571 | 14 | 0
0.176 | 134 | 6 | 0
0.63 | 168.9 | 10 | 0
0.314 | 251.7778 | 9 | 0
1.678 | 181.9524 | 21 | 0.183122
1.528 | 116.1053 | 19 | 0.147634
0.738 | 155.4545 | 11 | 0.132899
1.376 | 148.4706 | 17 | 0.128231
1.082 | 95.57143 | 14 | 0.178525
1.362 | 127.7059 | 17 | 0.149652
1.336 | 100.5 | 16 | 0.141197
1.006 | 136.1538 | 13 | 0.145879
1.88 | 199.8636 | 22 | 0.15596
0.698 | 74.41667 | 12 | 0.129044
1.334 | 100.5294 | 17 | 0.117198
1.256 | 104.9333 | 15 | 0.146
1.528 | 110.7368 | 19 | 0.129388
1.21 | 102.9333 | 15 | 0.158863
1.204 | 80.8 | 15 | 0.139957
1.988 | 152.5909 | 22 | 0.120701
1.06 | 117.1429 | 14 | 0.117962
1.47 | 147 | 18 | 0.136304
1.842 | 70.7619 | 21 | 0.13539
0.926 | 79.18182 | 11 | 0.118032
for regularization algorithm
plus, did you miss the decayed alpha in routers.py?

**Comment by jiechuanjiang** [comment]
The training episodes should be at least 2000

**Comment by yangyang-666** [comment]
请问，您在运行router.py的时候，tensorflow和keras都是什么版本呢？有没有出现运行错误？

**Comment by deLouvre** [comment]
> The training episodes should be at least 2000

Does the training episode refer to i_episode / 100 ?

**Comment by omarar** [comment]
> 请问，您在运行router.py的时候，tensorflow和keras都是什么版本呢？有没有出现运行错误？

Try:
pip install tensorflow==1.8.0
pip install keras==2.0.8

It works for me.
