### ISSUE TITLE
MAgent Configuration

### ISSUE THREAD

**Issue by Isaac009** [PKU-AI-Edge/DGN#4]
Sorry guys I tried to install MAgent to work with this repository it went but I couldn't figure out what to do with this instruction: Install MAgent and copy config folder to its installed folder. Where exactly can I find this _**installed folder**_ . I am using Ubuntu 18.04.

Thanks in advance.

**Comment by yinjiangjin** [comment]
Hi，@Isaac009, I face the same problem with you. If you address it, could you give me some advice? (I am using Ubuntu 18.04 too.)

**Comment by Isaac009** [comment]
> Hi，@Isaac009, I face the same problem with you. If you address it, could you give me some advice? (I am using Ubuntu 18.04 too.)

Hi @yinjiangjin, I followed the steps provided from this github repository (geek-ai/MAgent) https://github.com/geek-ai/MAgent, the folder which I cloned from that repository is the installed folder which readMe in this repository refers to (after installation), so I copied config folder to MAgent directory. But after that I got another error:     

os.mkdir(name)
FileNotFoundError: [Errno 2] No such file or directory: 'build/render'
